language: node_js
node_js:
- '0.10'
before_install:
  - 'npm install -g bower'
  - 'bower install'
after_script: npm run coveralls
env:
  global:
  - COVERALLS_REPO_TOKEN=sDYyXQ0lOh6zPDiGOKHrzpxosNPvUEhJ8
