language: node_js
node_js:
- '0.10'
before_install:
- npm install -g bower
- bower install
before_script:
- gulp lint
after_script:
- npm i -g codeclimate-test-reporter
- codeclimate < ./coverage/lcov.info
env:
  global:
  - secure: ahvnOEHpQNYh/iheqFEBy2mBhlQou4HaRg4y2R8ikAeMYpubTQWuRmJr/2n5BbrcdB5uXtkx6EKZzSpGPJJbZaklSM/CAcNMWNSbC9Dyu4g8L4ONSo7hFgaqNTEsXW1h4DvXBFlyOc2PwH7E9kaILXe+UDAMU8hHFd4vs7XEMCc=
